
spring:
  application:
    name: notification-service
  cloud:
    function:
      definition: accountConfirmListener
    stream:
      bindings:
        accountConfirmListener-in-0:
          destination: account-confirmation-notification
          binder: kafka
mail:
  host: smtp.gmail.com
  post: 587
  username: lahoavaco95@gmail.com
  password: toiggoahftuynndm
  protocol: smtp
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
server:
  port: 8040
